version: '3'

services:
  frontend-teste-bonaparte:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-teste-bonaparte
    ports:
      - "3000:5000"
    networks:
      - bonaparte-network
  backend-teste-bonaparte:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-teste-bonaparte
    environment:
      - MONGO_URI=mongodb+srv://axeljunior:semsenha@cluster0.ack1z.mongodb.net/teste-bonaparte?retryWrites=true&w=majority
    ports:
      - "3333:3333"
    networks:
      - bonaparte-network

networks:
  bonaparte-network:
    driver: bridge
